name: Chirpy
version: 2.7.1
homepage: https://github.com/cotes2020/jekyll-theme-chirpy/
favicon_name: calligraphy
favicon: https://thenounproject.com/search/?q=calligraphy&i=1606333
favicon_site: https://thenounproject.com/